name: Wokwi CI

on: [push]

jobs:
  wokwi:
    runs-on: ubuntu-latest

    steps:
      - name: Repo'yu klonla
        uses: actions/checkout@v3

      - name: Wokwi ile test et
        uses: wokwi/wokwi-ci-action@v1
        with:
          token: ${{ secrets.WOKWI_CLI_TOKEN }}
          path: .  # wokwi.toml dosyası bu klasördeyse
          expect_text: 'LED ON'  # Seri çıktıda beklenen yazı
