name: Wokwi Simulation

on: [push]

jobs:
  wokwi:
    runs-on: ubuntu-latest

    steps:
      - name: Repo'yu klonla
        uses: actions/checkout@v3

      - name: Wokwi CLI'yi indir ve kur (x64 sabit link)
        run: |
          wget https://github.com/wokwi/wokwi-cli/releases/download/v0.15.3/wokwi-cli-linuxstatic-x64 -O wokwi-cli
          chmod +x wokwi-cli

      - name: Simülasyonu çalıştır
        run: |
          ./wokwi-cli run --timeout 10000 --check "LED ON" --project diagram.json
