name: Wokwi Simulation

on: [push]

jobs:
  wokwi:
    runs-on: ubuntu-latest

    steps:
      - name: Repo'yu klonla
        uses: actions/checkout@v3

      - name: Wokwi CLI'yi indir ve hazırla
        run: |
          curl -s https://api.github.com/repos/wokwi/wokwi-cli/releases/latest \
          | grep "browser_download_url" \
          | grep "linux" \
          | cut -d '"' -f 4 \
          | wget -i -
          chmod +x wokwi-cli-*-linux
          mv wokwi-cli-*-linux wokwi-cli

      - name: Simülasyonu çalıştır
        run: |
          ./wokwi-cli run --timeout 10000 --check "LED ON" --project diagram.json
